name: zapfull-security-scan
on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: staging
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://amorservtech.net/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
